### ISSUE TITLE
Errors referencing file in /code/ directory

### ISSUE THREAD

**Issue by Bobert-Brockson** [Waayway/nixos-waayway#1]
See [this line](https://github.com/Waayway/nixos-waayway/blob/672a74c0e955b0ef2e787adbd67a3afe0ecc4263/flake.nix#L13) which causes an error on my machine (and probably any new machine)

**Comment by Waayway** [comment]
Hi, this is just my config, i am currently not even on nix anymore, so... its single line  to change it or just remove wam since im not using it anyways
